global:
  scrape_interval:     10s
  evaluation_interval: 10s

rule_files:
  - 'alert.rules'
  # - "first.rules"
  # - "second.rules"
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.194.129:9090']

  - job_name: 'system'
    static_configs:
      - targets: ['node_exporter:9100']


  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'auth-microservice'
    static_configs:
      - targets: ['192.168.194.129:7070']
